name: AZola to GitHub Pages

on: 
 push:
  branches:
   - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: berdandy/zola-deploy-action@v0.5.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: accessibilitywars/aw2-builds
        PAGES_BRANCH: main
        TOKEN: ${{ secrets.TOKEN }}
        # CHECK_LINKS: true
        BUILD_THEMES: false
        # BUILD_FLAGS: --drafts
