# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          REPOSITORY: accessibilitywars/builds
          PAGES_BRANCH: main
          TOKEN: ${{ secrets.TOKEN }}
          CHECK_LINKS: true
          BUILD_THEMES: false
          # BUILD_FLAGS: --drafts
