name: Zola on GitHub Pages

on: 
 push:
  branches:
   - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.18.0
        env:
          REPOSITORY: accessibilitywars/builds
          PAGES_BRANCH: master
          TOKEN: ${{ secrets.TOKEN }}
          CHECK_LINKS: true
          BUILD_THEMES: false
          # BUILD_FLAGS: --drafts
